import React, { useState, useEffect } from "react";
import { FaGithub } from "react-icons/fa";
import { IoLogoVercel } from "react-icons/io5";
import ProjectCard from "./ProjectCard";
import MosaicProject from "./MosaicProject";

import './project.css';

const Project = () => {
    // Estados para os filtros
    const [activeTypeFilter, setActiveTypeFilter] = useState('Todos');
    const [activeTechFilter, setActiveTechFilter] = useState('Todos');
    const [selectedProject, setSelectedProject] = useState(null);

    // Dados dos projetos
    const projects = [
        {
            id: 1,
            title: "Sistema de Mercado Interno",
            date: "",
            skills: ["Java", "Spring Boot", "React", "TypeScript", "PostgreSQL", "Docker", "JWT", "Tailwind CSS"],
            shortDescription: "Ecossistema integrado com totem, portal do colaborador e dashboard administrativo para mais de 300 colaboradores.",
            description: "Ecossistema completo para o mercado interno da Concessionária Tamoios: totem de autoatendimento estilo McDonalds, portal do colaborador e dashboard administrativo. Adotado por mais de 300 colaboradores, economizando 25 horas mensais da equipe de gestão.",
            backgroundUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
            size: "large",
        },

        {
            id: 2,
            title: "STUP — Sistema de Transporte Público",
            date: "11/2024",
            skills: ["Node", "Express", "MySQL", "Bootstrap", "JavaScript"],
            shortDescription: "Sistema de gestão de transporte público com usuários, cartões, ônibus, motoristas e painel administrativo.",
            description: "Sistema de transporte público reconstruído do zero após perda do projeto original por falta de versionamento. Inclui gerenciamento de usuários, cartões, motoristas, ônibus e dashboard administrativo.",
            backgroundUrl: "/assets/full-stack-estudo-javascript-mvc2.png",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "https://github.com/JGabrielFBeserra/STUP",
            size: "large",
        },

        {
            id: 3,
            title: "Dataset de Fauna — Visão Computacional",
            date: "2025",
            skills: ["Python", "Deep Learning", "YOLO", "Visão Computacional", "Anotação de Dados", "Machine Learning"],
            shortDescription: "Pipeline de visão computacional para monitoramento automatizado de fauna na Serra do Mar.",
            description: "Pesquisa aplicada em parceria entre IFSP-CAR e Concessionária Tamoios para monitoramento automatizado de fauna na Serra do Mar.",
            backgroundUrl: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
            size: "large",
        },

        {
            id: 4,
            title: "BioDex — Parque Natural Juqueriquerê",
            date: "jan–jun 2024",
            skills: ["Node.js", "React Native", "PostgreSQL", "JWT", "Socket.io", "Expo", "Tamagui"],
            shortDescription: "Totens digitais, app mobile e gamificação para gestão de visitas e educação ambiental.",
            description: "Sistema desenvolvido em parceria com prefeitura, incluindo QR Codes, rankings, exportações e dashboard.",
            backgroundUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "https://lnkd.in/gbBcms8D",
            gitHubLink: "",
            size: "large",
        },

        {
            id: 5,
            title: "Sistema Controle de Ponto",
            date: "05/2025",
            skills: ["MVC", "API REST", "JWT", "Javascript", "Prisma"],
            shortDescription: "Controle acadêmico de frequência com autenticação, CRUD e relatórios automatizados.",
            description: "Sistema acadêmico de controle de frequência com autenticação JWT, CRUD completo e geração de relatórios PDF.",
            backgroundUrl: "/assets/full-stack-estudo-javascript-mvc.png",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "https://github.com/JGabrielFBeserra/sistema-controle-ponto",
            size: "large",
        },
        {
            id: 6,
            title: "Portfolio React",
            date: "07/2025",
            type: "Aplicados",
            tech: "Frontend",
            skills: ["React", "Javascript", "CSS3", "Vite", "Hooks"],
            description: "Portfólio profissional construído com React e Vite em 2 semanas. Tema claro/escuro, scroll com navegação ativa e layout responsivo com CSS Grid.",
            backgroundUrl: "/assets/frontend-aplicado-react.png",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "https://jgabrielfbeserra.vercel.app/",
            gitHubLink: "https://github.com/JGabrielFBeserra/Portifolio-ReactJS",
            size: "normal"
        },
        {
            id: 7,
            title: "API Transações Itaú",
            date: "01/2025",
            type: "Estudos",
            tech: "Backend",
            skills: ["Java", "Spring Boot", "API REST", "Swagger", "Logs"],
            description: "Desafio técnico do Itaú: API REST em Java 21 e Spring Boot que processa transações e calcula estatísticas em tempo real com documentação Swagger.",
            backgroundUrl: "/assets/backend-estudo-java.jpg",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "https://github.com/JGabrielFBeserra/Estudo-TesteDevJuniorJava-BancoItau",
        },
        {
            id: 8,
            title: "OnePage Bootstrap",
            date: "06/2024",
            type: "Aplicados",
            tech: "Frontend",
            skills: ["Bootstrap", "JavaScript", "CSS3", "HTML5"],
            description: "One-page para mapear iniciativas de reciclagem com CRUD local em JS puro. Serviu também como prova de proficiência na disciplina de Desenvolvimento Web 1.",
            backgroundUrl: "/assets/frontend-estudo-javascript.png",
            gifUrl: "/assets/frontend-estudo-javascript.gif",
            videoUrl: "https://youtu.be/-d78wj6wEzM",
            siteUrl: "https://portal-coscientizacao-reciclagem-bo.vercel.app/",
            gitHubLink: "https://github.com/JGabrielFBeserra/Portal-Coscientizacao-Reciclagem-Bootstrap.git",
        },
        {
            id: 9,
            title: "Leitor de Código de Barras na Tela",
            date: "01/2025",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "OpenCV", "Automação", "OCR", "RPA"],
            description: "Interface transparente que lê códigos de barras diretamente da tela via hotkey e copia para a área de transferência. Eliminou a compra de leitor físico no setor financeiro.",
            backgroundUrl: "/assets/backend-aplicado-barcode.png",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "https://github.com/JGabrielFBeserra/print-codigodebarras-automation",
        },
        {
            id: 10,
            title: "PDF to Excel Automation",
            date: "05/2025",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "Automação", "Excel", "PDF", "RPA"],
            description: "Extrai ordens de serviço de PDFs para Excel 120x mais rápido que o processo manual. Desenvolvido em uma semana com pdfplumber e openpyxl.",
            backgroundUrl: "/assets/backend-aplicado-pdf-to-excel.png",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "https://github.com/JGabrielFBeserra/PDF-to-Excel-Automation",
        },
        {
            id: 11,
            title: "GLPI Card Export",
            date: "01/2025",
            type: "Aplicados",
            tech: "Frontend",
            skills: ["JavaScript", "Chrome API", "DOM", "PDF"],
            description: "Extensão Chrome que gera PDFs com evidências de chamados GLPI, reduzindo 80% do tempo de documentação da equipe de TI.",
            backgroundUrl: "/assets/backend-aplicado-glpi-card.png",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "https://github.com/JGabrielFBeserra/glpi-.card-body-downloader",
        },
        {
            id: 12,
            title: "Avaliador de Hackathon",
            date: "",
            type: "Aplicados",
            tech: "Full Stack",
            skills: ["PHP", "WordPress", "MySQL", "Plugin"],
            description: "Plugin WordPress desenvolvido em dupla para avaliação estruturada de projetos durante hackathon, com critérios customizados e interface administrativa.",
            backgroundUrl: "/assets/full-stack-aplicado-hack.png",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
        },
        {
            id: 13,
            title: "Fatura Extractor Automation",
            date: "07/2025",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "PDF", "Automação", "Excel", "OCR"],
            description: "Extrai dados de centenas de faturas de energia mensais, separando canhotos e renomeando arquivos. Suporta CEDRAP, ELEKTRO e EDP.",
            backgroundUrl: "/assets/backend-aplicado-faturas.png",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "https://github.com/JGabrielFBeserra/fatura-extractor-automation",
        },
        {
            id: 14,
            title: "Automação PDFs → Planilhas com Pandas",
            date: "08/2025",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "Pandas", "PDF", "Excel", "RPA"],
            description: "Entregue no mesmo dia da solicitação: extrai colunas de PDFs por coordenadas BBox e exporta planilha estruturada com Pandas.",
            backgroundUrl: "/assets/backend-aplicado-pdf.png",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "https://github.com/JGabrielFBeserra/pdf-to-excel-pandas",
        },
        {
            id: 15,
            title: "Download Automático de Anexos GLPI",
            date: "08/2025",
            type: "Aplicados",
            tech: "Frontend",
            skills: ["JavaScript", "Chrome API", "Automação", "UX"],
            description: "Extensão para baixar múltiplos anexos de chamados GLPI de uma vez. Economia de ~144 horas anuais por colaborador no setor de Contas a Pagar.",
            backgroundUrl: "/assets/full-backend-aplicado-javascript-glpi.png",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "https://github.com/JGabrielFBeserra/glpi-pdf-excel-downloader",
        },
        {
            id: 16,
            title: "Exportação de Prévia Diária + Resumo",
            date: "",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "Automação", "RPA", "Backoffice"],
            description: "Automação da exportação e consolidação da prévia diária no CCA. Parte de um pacote que economiza 48 horas anuais por colaborador.",
            backgroundUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
        },
        {
            id: 17,
            title: "Exportação Volume Pedagiado",
            date: "",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "Automação", "RPA", "Backoffice"],
            description: "Extração e exportação automática do volume pedagiado no CCA, eliminando intervenção manual e padronizando a saída dos dados de arrecadação.",
            backgroundUrl: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
        },
        {
            id: 18,
            title: "Exportação TXT das Evasões",
            date: "",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "Automação", "RPA", "Backoffice"],
            description: "Geração e exportação automática do arquivo TXT de evasões no CCA, garantindo padronização e rastreabilidade sem intervenção manual diária.",
            backgroundUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
        },
        {
            id: 19,
            title: "Exportação Fechamento Mensal",
            date: "",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "Automação", "RPA", "Backoffice"],
            description: "Executa automaticamente todas as exportações do fechamento mensal do CCA, eliminando risco de atrasos em janelas de tempo restritas.",
            backgroundUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
        },
        {
            id: 20,
            title: "Automatização de Criação de Pastas",
            date: "",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "Automação", "RPA", "OS"],
            description: "Gera estruturas de pastas padronizadas com nomes dinâmicos baseados em datas, eliminando inconsistências de nomenclatura no CCA.",
            backgroundUrl: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
        },
        {
            id: 21,
            title: "Extração de NFs com OCR e IA",
            date: "",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "OCR", "IA", "PDF", "RPA"],
            description: "Leitura inteligente de Notas Fiscais em PDF com OCR e IA, extraindo automaticamente os campos relevantes. Parte do pacote que economiza +120 horas anuais no financeiro.",
            backgroundUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
        },
        {
            id: 22,
            title: "Download com Renomeação Automática",
            date: "",
            type: "Aplicados",
            tech: "Frontend",
            skills: ["JavaScript", "Chrome API", "Automação", "DOM"],
            description: "Extensão Chrome que intercepta downloads e aplica nomenclatura padrão do financeiro automaticamente, eliminando a etapa manual de renomeação.",
            backgroundUrl: "https://images.unsplash.com/photo-1573867639040-6dd25fa5f597?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
        },
        {
            id: 23,
            title: "Extração de OSs para .xlsx",
            date: "",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "PDF", "Excel", "Automação", "RPA"],
            description: "Extrai dados de Ordens de Serviço em PDF direto para Excel com formatação e fórmulas automáticas conforme padrão do setor financeiro.",
            backgroundUrl: "https://images.unsplash.com/photo-1543286386-713bdd548da4?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
        },
        {
            id: 24,
            title: "Automação Resumos e Fechamento CCA",
            date: "05/2026",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "Pandas", "OpenPyXL", "RPA"],
            description: "Gera resumos diários individuais e consolida ~30 arquivos mensais em um único fechamento. Eliminou o esforço manual de manipulação de planilhas no CCA.",
            backgroundUrl: "https://images.unsplash.com/photo-1599658880436-c61792e70672?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
        },
        {
            id: 25,
            title: "Pipeline IQA — Dados Ambientais",
            date: "05/2026",
            type: "Aplicados",
            tech: "Backend",
            skills: ["Python", "pdfplumber", "python-docx", "OpenPyXL"],
            description: "Extrai dados de PDFs do Índice de Qualidade das Águas e exporta para DOCX e Excel automaticamente. Desenvolvido em 8h, economiza 6h de trabalho manual por trimestre.",
            backgroundUrl: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "",
        },
        {
            id: 26,
            title: "Montador de Lanche — Vue.js",
            date: "",
            type: "Estudos",
            tech: "Frontend",
            skills: ["Vue", "JavaScript", "Bootstrap"],
            description: "App Vue.js para montar lanches com preview em tempo real. Criado para aprender reatividade, v-model e computed properties fora do ecossistema React.",
            backgroundUrl: "/assets/frontend-estudo-vue.png",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "https://github.com/JGabrielFBeserra/Estudo-de-VueJS",
        },
        {
            id: 27,
            title: "OnePage Bootstrap — Inglês",
            date: "05/2024",
            type: "Estudos",
            tech: "Frontend",
            skills: ["Bootstrap", "Responsividade", "HTML", "SCSS"],
            description: "Site institucional criado como substituto de slides para apresentação de empresa fictícia na disciplina de inglês. Concluído em 3 dias.",
            backgroundUrl: "/assets/frontend-estudo-bootstrap.png",
            gifUrl: "",
            videoUrl: "",
            siteUrl: "",
            gitHubLink: "https://github.com/JGabrielFBeserra/OnePage-Bootstrap",
        },
    ];


    function getEmbedUrl(videoUrl) {
        if (videoUrl.includes("youtu.be")) { //verifica se é um link curto do youtube
            const id = videoUrl.split("/").pop().split("?")[0]; //se for eu uso o split para pegar o id do video
            return `https://www.youtube.com/embed/${id}`; //retorno com o embed para funcioar no iframe
        }

        if (videoUrl.includes("watch?v=")) { //verifica se é um link longo do youtube
            const id = new URL(videoUrl).searchParams.get("v"); //extraio o id do video
            return `https://www.youtube.com/embed/${id}`; //retorno com o embed para funcioar no iframe
        }

        return videoUrl;
    }



    return (
        <div className="project__container container">
            <div className="project__content" >
                <MosaicProject projects={projects} />
            </div>

        </div>

    );
}

export default Project;